mypro/urls.py
from django.urls import path
from mypro import views

app_name="mypro"
urlpatterns = [
    path('home', views.home, name='home'),
    path('about', views.about, name='about'),
    path('blog_single', views.blog_single, name='blog_single'),
    path('blog', views.blog, name='blog'),
    path('contact', views.contact, name='contact'),
    path('index', views.index, name='index'),
    path('portfolio', views.portfolio, name='portfolio'),
    


    path('base', views.base, name = 'base'),
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login_reg'),
    path('logout', views.logoutuser, name = 'logout'),

    path('product', views.product, name='product'),
    path('products', views.products, name='products'),
    path('order/<int:id>', views.order, name='order'),
    path('kart', views.kart  , name='kart '),
   
]

protfolio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mypro.urls')),
]

mypro/models.py
from django.db import models

# Create your models here.


class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=50)
    description = models.TextField(default='Its too yummy')
    image = models.ImageField(upload_to='images')
    order_status = models.BooleanField(default=False)
    items = models.IntegerField(default=0)

    def __str__(self):
        return self.name

mypro/forms.py


from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
		

from django import forms
from .models import  Product



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

class OrderForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['order_status', 'items']


mypro/views.py

from django.shortcuts import render, redirect, get_object_or_404


## for user creation or register, sign-in and sign-out.
from django.shortcuts import render, redirect
from mypro.forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required 
 

def register(request):	
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Your Account has been created for '+ user)
			return redirect('mypro:login_reg')


	context = { 'form': form }
	return render (request, 'signin/register.html', context)


def login_reg(request):

	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username = username, password = password)
		if user is not None:
			login(request, user)
			return redirect('mypro:base')
		else:
			messages.info(request, "Username Or password is incorrect.")


	context = {}
	return render (request, 'signin/login_reg.html', context)

def logoutuser(request):
	logout(request)
	# return redirect('mypro:login_reg')
	return redirect('mypro:base')


@login_required(login_url = 'mypro:login_reg')
def base(request):
	return render (request,"signin/base.html", context = {})



from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')


def blog_single(request):
    return render(request,'blog_single.html')

def blog(request):
    return render(request,'blog.html')


def contact(request):
    return render(request,'contact.html')

def index(request):
    return render(request,'index.html')

def portfolio(request):
    return render(request,'portfolio.html')

from .forms import ProductForm, OrderForm
from .models import Product


def product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            return render(request, 'imageapp\product.html', {'form': form, 'img_obj': img_obj})
    else:
        form = ProductForm()
    return render(request, 'imageapp\product.html', {'form': form})

def products(request):
    all_products=Product.objects.all()
    context={'all_products':all_products}
    return render(request, 'imageapp\products.html', context)

def order(request, id):
    obj = get_object_or_404(Product, id =id)
    form = OrderForm(request.POST or None, instance = obj)
    data = Product.objects.get(id = id)
    if form.is_valid():
        form.save()
        return redirect('products')
    context = {'form':form, 'data':data}
    return render(request, 'imageapp/order.html', context)

def kart(request):
    Ordered_items = Product.objects.filter(order_status = True)
    print("Ordered Items :", Ordered_items)
    price = Product.objects.values('price')[0]
    total = 0
    total_value = 0
    for price in Ordered_items:
        print(price.price)
        print(price.items)
        total = price.price*price.items
        total_value = total_value+total
        print(total)

    print(total_value)
    context = {'Ordered_items':Ordered_items, 'total':total_value}
    return render(request, 'imageapp/kart.html', context)

templates/about.html
{% load static %}
<!DOCTYPE html>

<!--
 // WEBSITE: https://themefisher.com
 // TWITTER: https://twitter.com/themefisher
 // FACEBOOK: https://www.facebook.com/themefisher
 // GITHUB: https://github.com/themefisher/
-->

<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Kross - Creative Portfolio Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Creative Portfolio Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Kross Template v1.0">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{%  static 'plugins/themify-icons/themify-icons.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
  

<header class="navigation fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand font-tertiary h3" href="index.html"><img src="{% static 'images/logo.png' %}" alt="Myself"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="index.html">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about.html">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="blog.html">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="portfolio.html">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!-- page title -->
<section class="page-title-alt bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-white font-tertiary">About Me</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{% static 'images/illustrations/leaf-bg-top.png' %}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{% static 'images/illustrations/dots-group-sm.png' %}" alt="illustrations" class="bg-shape-2">
  <img src="{% static 'images/illustrations/leaf-yellow.png' %}" alt="illustrations" class="bg-shape-3">
  <img src="{% static 'images/illustrations/leaf-orange.png' %}" alt="illustrations" class="bg-shape-4">
  <img src="{% static 'images/illustrations/dots-group-cyan.png' %}" alt="illustrations" class="bg-shape-5">
  <img src="{% static 'images/illustrations/leaf-cyan-lg.png' %}" alt="illustrations" class="bg-shape-6">
</section>
<!-- /page title -->

<!-- about -->
<section class="section pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <p>
          I am a hardworking and ambitious individual with a great passion for the software developer and application designing.<br> 
          I am currently in my fourth year of studying B.E in the stream of 'COMPUTER SCIENCE AND ENGINEERING (CSE)'at DHANALAKSHMI COLLEGE OF ENGINEERING,CHENNAI.<br>
           I have excellent communication skills, enabling me to effectively communicate with a wide range of people.<br>
           I am seeing a full-time position in the industry in which I can put into practice my knowledge and experience,<br> ultimately benefiting the operations of the organisation that I work for.
          I want to become a highly competent IT professional with a proven track record in designing websites, networking and managing databases.<br>
           I have strong technical skills as well as excellent interpersonal skills, enabling me to interact with a wide range of clients. 
           I am eager to be challenged in order to grow and further improve my IT skills. My greatest passion is in life is using my technical know-how to benefit other people,organisation and it's goals.<br>
           I am able to handle multiple tasks on a daily basis.I use a creative approach to problem solving.
        </p>
      </div>
      <div class="col-md-4 text-center drag-lg-top">
        <div class="shadow-down mb-4">
          <img src="{% static 'images/about/nikhil.jpg' %}" alt="author" class="img-fluid w-100 rounded-lg border-thick border-white">
        </div>
        <img src="{% static 'images/about/signature.jpg'%}" alt="signature" class="img-fluid">
        <h4>NIKHIL</h4>
      </div>
    </div>
  </div>
</section>
<!-- /about -->

<!-- Work Process -->
<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Work Process</h2>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <div class="">
          <img src="{% static 'images/icons/plan.png' %}" class="mb-4" alt="icon">
          <h4 class="mb-4">Research and Plan</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static 'images/icons/design.png' %}" class="mb-4" alt="icon">
        <h4 class="mb-4">Design and Develop</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
      <div class="col-lg-3 col-md-4 text-center hover-shadow pt-3">
        <img src="{% static 'images/icons/print.png'%}" class="mb-4" alt="icon">
        <h4 class="mb-4">Deliver</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua.</p>
      </div>
    </div>
  </div>
</section>
<!-- ./Work Process -->

<!-- team -->
<section class="section bg-cover" data-background="images/backgrounds/team-bg.png">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Team</h2>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/about/pinky.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">PINKY</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/about/nikitha.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">NIKITHA</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 mb-4 mb-md-0">
        <div class="card text-center">
          <img src="{% static 'images/about/vamsi.jpg' %}" class="card-img-top">
          <div class="card-body">
            <h4 class="card-title">VAMSI</h4>
            <p class="text-light font-secondary">Project Manager</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /team -->

<!-- clients -->
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">My Clients</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="client-logo-slider d-flex align-items-center">
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-1.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-2.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-3.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-4.png' %}" alt="client-logo"></a>
          <a href="contact.html" class="text-center d-block outline-0 p-4"><img class="d-unset img-fluid"
              src="{%  static 'images/clients-logo/client-logo-5.png' %}" alt="client-logo"></a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /clients -->

<!-- contact -->
<section class="section section-on-footer" data-background="images/backgrounds/bg-dots.png">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h2 class="section-title">Contact Info</h2>
      </div>
      <div class="col-lg-8 mx-auto">
        <div class="bg-white rounded text-center p-5 shadow-down">
          <h4 class="mb-80">Contact Form</h4>
          <form action="#" class="row">
            <div class="col-md-6">
              <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-md-6">
              <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
            </div>
            <div class="col-12">
              <textarea name="message" id="message" class="form-control px-0 mb-4"
                placeholder="Type Message Here" required></textarea>
            </div>
            <div class="col-lg-6 col-10 mx-auto">
              <button class="btn btn-primary w-100">send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /contact -->

<!-- footer -->
<footer class="bg-dark footer-section">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5 class="text-light">Email</h5>
          <p class="text-white paragraph-lg font-secondary">nikhilillapu7@email.com</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Phone</h5>
          <p class="text-white paragraph-lg font-secondary">7396475989</p>
        </div>
        <div class="col-md-4">
          <h5 class="text-light">Address</h5>
          <p class="text-white paragraph-lg font-secondary">125/A, NELLORE, AP</p>
        </div>
      </div>
    </div>
  </div>
  <div class="border-top text-center border-dark py-5">
    <p class="mb-0 text-light">Copyright &copy;<script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> Designed &amp; Developed by <a class="text-white-50" href="{% static 'Themefisher' %}">Themefisher</a></p>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/base.html
{% block content %}

{% endblock %}

templates/home.html
<div class="collapse navbar-collapse text-center" id="navigation">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">about</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio' %}">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
  </div>

  this is a home page.

templates/imageapp/kart.html
{% extends 'base.html' %}  


{% block content %}

  
  {% if Ordered_items %}
        {% for Ordered_items in Ordered_items %}
    <h3>ordered items: {{Ordered_items.name}}</h3>
    <img src="{{ Ordered_items.image.url}}" alt="connect" style="max-height:100px">
    <h3>Order status : {{Ordered_items.order_status}}</h3>
                    <h3>Price : {{Ordered_items.price}}</h3>
                    <h3>Quantity : {{Ordered_items.items}}</h3>
                    
        {% endfor %}
  {% endif %}
  <a href="products">Change the order. </a>
<br><br>
<hr>
<h1>
    Total price : {{total}}
</h1>
<hr>
{% endblock %}

templates/imageapp/order.html
{% extends 'base.html' %}     

{% block content %}  


                {% if data %}  
                    <h3>Name : {{data.name}}</h3>  
                    <img src="{{ data.image.url}}" alt="connect" style="max-height:100px">
                    <h3>Dscription : {{data.description}}</h3>
                    <h3>Order status : {{data.order_status}}</h3>
                    <h3>Price : {{data.price}}</h3>
                    <h3>Quantity : {{data.items}}</h3>
                        <hr>
                {% endif %}  
                <form method="POST">
                    {% csrf_token %}
                    
                    <div>
                        <h1>Enter the number of items for order.</h1>
                       <h3>Quantity:{{ form.items}} </h3> 
                      <h3> Order status:  {{form.order_status}} </h3>
                    </div>
                
                        <input type="submit" value="Yes, Update" />
                        <a href="/">Cancel </a>
                    </form>
                    
        
{% endblock content %}   

templates/imageapp/product.html
{% extends 'base.html' %}  


{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
  
  {% if img_obj %}
    <h3>Succesfully uploaded : {{img_obj.name}}</h3>
    <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:100px">
  {% endif %}


{% endblock %}

templates/imageapp/products.html
{% extends 'base.html' %}     

{% block content %}  


        {% for img_obj in all_products %}
                {% if img_obj %}  
                    <h3>Name : {{img_obj.name}}</h3>  
                    <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:100px">
                    <h3>Dscription : {{img_obj.description}}</h3>
                    <h3>Order status : {{img_obj.order_status}}</h3>
                    <h3>Price : {{img_obj.price}}</h3>
                    <h3>Quantity : {{img_obj.items}}</h3>
                    
                    <a href = "order/{{ img_obj.id }}"  button class="button button1">Order</button><br><br>
                    <a href = "kart"  button class="button button1">Kart</button>
                    
                        <hr>
                {% endif %}  

        {% endfor %}

{% endblock content %}   

templates/signin/base.html
<h1>Home Page</h1>

Hello {{ user }}

<a href="{% url 'mypro:logout' %}">Logout </a>

templates/signin/login_reg.html


<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


  <style>
    body,
    html {
      margin: 0;
      padding: 0;
      height: 100%;
      background: #7abecc !important;
    }
    .user_card {
      width: 350px;
      margin-top: auto;
      margin-bottom: auto;
      background: #74cfbf;
      position: relative;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding: 10px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 5px;

    }

    .form_container {
      margin-top: 20px;
    }

    #form-title{
      color: #fff;
      
    }

    .login_btn {
      width: 100%;
      background: #33ccff !important;
      color: white !important;
    }
    .login_btn:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }
    .login_container {
      padding: 0 2rem;
    }
    .input-group-text {
      background: #f7ba5b !important;
      color: white !important;
      border: 0 !important;
      border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }

    #messages{
      background-color: grey;
      color: #fff;
      padding: 10px;
      margin-top: 10px;
    }
  </style>

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">


          <h3 id="form-title">LOGIN</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="login_reg">
            {% csrf_token %}
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
                <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login">
                </div>
          </form>

        </div>
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'mypro:register' %}" class="ml-2">Sign Up</a>
          </div>
      
        </div>
      </div>
    </div>
  </div>
</body>

</html>